import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.HER_PLAYWRIGHT_MODULE || 'playwright');
const origin = process.env.HER_OPERATOR_TEST_ORIGIN || 'http://127.0.0.1:5190';
if (!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin)) throw new Error('UI QA requires an isolated local preview.');
const output = '.impeccable/review';
await mkdir(output, { recursive: true });
const positions = Array.from({ length: 13 }, (_, index) => ({ mint: String(index + 2).repeat(32), name: index === 0 ? 'Synthetic QA: A Very Long Community Token Name With Unusually Long Words' : `Synthetic QA Coin ${index + 1}`, symbol: index === 0 ? 'VERYLONGTICKER' : `TEST${index + 1}`, logo: index < 3 ? `${origin}/olivia-icon.png` : null, amount: index === 12 ? 0 : 123456.789, bought: true, priceQuote: 0.0008, valueSol: index === 12 ? 0 : index === 2 ? null : 0.63, costSol: index === 2 ? null : index === 12 ? 0 : 0.4, realizedSol: 0.1, unrealizedSol: index === 2 ? null : 0.23, pnlSol: index === 2 ? null : index === 1 ? -0.12 : 0.33, pnlPercent: index === 2 ? null : index === 1 ? -30 : 82.5, boughtSol: 0.4 }));
const fixture = { status: 'live', readOnly: true, wallet: '1'.repeat(32), observedAt: Date.now(), startingSol: 3, solBalance: 1.2356, wrappedSolBalance: 0, equitySol: 4.2862, equityQuote: 642.93, solPriceQuote: 150, quoteCurrency: 'USDC', pnlSol: 1.2862, pnlPercent: 42.8733, realizedSol: 0.4862, unrealizedSol: 0.8, positions, activity: positions.map((coin, index) => ({ ...coin, signature: 'ABCDEFGHJKLMN'[index].repeat(88), timestamp: Date.now() - index * 60000, side: index % 3 ? 'buy' : 'sell', amount: 20000, solAmount: 0.2 })), warnings: ['prices_missing'] };
// Fixtures are only intercepted browser responses, never shipped as wallet data.
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  page.on('pageerror', error => errors.push(error.message));
  let mode = 'actual';
  await page.route('**/api/her?*', async route => route.fulfill({ json: { now: Date.now(), online: false, accepting: false, control: { enabled: false, desired: 'olivia', actual: 'olivia' }, totals: [], recent: [], enabled: false, stageEnabled: false, voting: false, mint: '', symbol: 'HER', turnkeyOrganizationId: '', turnkeyAuthProxyConfigId: '', round: null, candidates: [], history: [] } }));
  await page.route('**/api/trades', async route => mode === 'actual' ? route.continue() : mode === 'error' ? route.fulfill({ status: 503, json: { error: 'Unavailable' } }) : route.fulfill({ json: fixture }));
  await page.goto(`${origin}/#trades`, { waitUntil: 'networkidle' });
  const section = page.locator('#trades');
  await section.getByText('Waiting for the first trade.', { exact: true }).waitFor();
  await page.addStyleTag({ content: 'nextjs-portal { display: none !important; }' });
  assert.equal(await page.locator('a[href*="/operator/"]').count(), 0);
  const actual = await (await page.request.get(`${origin}/api/trades`)).json();
  assert.equal(actual.status, 'paused');
  assert.equal(actual.startingSol, 3);
  assert.equal(actual.solBalance, null);
  assert.ok(!JSON.stringify(actual).match(/operator|password|sessionSecret|privateKey|thesis/i));
  await section.screenshot({ path: `${output}/trades-paused-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await section.screenshot({ path: `${output}/trades-paused-mobile.png` });
  mode = 'live';
  await section.getByRole('button', { name: 'Refresh wallet data' }).click();
  await section.getByRole('tab', { name: 'Open positions 12', exact: true }).waitFor();
  assert.equal(await section.locator('tbody tr').count(), 10);
  await section.getByRole('button', { name: 'Next page', exact: true }).click();
  assert.equal(await section.locator('tbody tr').count(), 2);
  await section.getByRole('button', { name: 'Previous page', exact: true }).click();
  await section.locator('img').evaluateAll(async images => Promise.all(images.map(image => image.decode().catch(() => {}))));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await section.screenshot({ path: `${output}/trades-desktop.png` });
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await section.screenshot({ path: `${output}/trades-mobile.png` });
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    const layout = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, images: [...document.querySelectorAll('#trades img')].map(img => img.complete && img.naturalWidth > 0), controls: [...document.querySelectorAll('#trades button')].filter(button => button.getBoundingClientRect().width > 0).map(button => ({ width: button.clientWidth, scroll: button.scrollWidth })), overlay: !!document.querySelector('[data-nextjs-dialog], .vite-error-overlay') }));
    assert.ok(layout.scroll <= layout.width, `No document overflow at ${width}`);
    assert.ok(layout.controls.every(control => control.scroll <= control.width + 1), `Button labels fit at ${width}`);
    assert.ok(layout.images.every(Boolean), 'Metadata logos and HER asset rendered');
    assert.equal(layout.overlay, false);
  }
  await section.getByRole('tab', { name: 'Closed positions 1', exact: true }).click();
  assert.equal(await section.locator('tbody tr').count(), 1);
  await section.getByRole('tab', { name: 'Trade history 13', exact: true }).click();
  await section.getByRole('link', { name: 'View sell transaction' }).first().waitFor();
  await section.screenshot({ path: `${output}/trades-history-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await section.screenshot({ path: `${output}/trades-history-mobile.png` });
  await section.getByRole('tab', { name: 'Open positions 12', exact: true }).click();
  await section.getByRole('tab', { name: 'Open positions 12', exact: true }).press('ArrowRight');
  assert.equal(await section.getByRole('tab', { name: 'Closed positions 1', exact: true }).getAttribute('aria-selected'), 'true');
  mode = 'error';
  await section.getByRole('button', { name: 'Refresh wallet data' }).click();
  await section.getByRole('alert').filter({ hasText: 'Previously checked data is shown.' }).waitFor();
  assert.equal(await section.locator('tbody tr').count(), 1);
  assert.deepEqual(errors, []);
  console.log('PASS: Edge Trades paused/live/error states, real read-only API, public privacy, positive/negative/unknown P&L, pagination, closed positions, receipts, keyboard tabs and five responsive widths. Synthetic trades only.');
} finally { await browser.close(); }
