"use client";
import { useEffect,useRef,useState } from 'react';
import { characters,shortWallet,type Character } from '@/lib/catalog';
import { api,useWallet,WalletRoot } from '@/components/wallet';
import { voteAmount } from '@/lib/burn-amount';
import { VotingPanel,useVoting,type Voting } from '@/components/voting';
import TradesPanel from '@/components/trades-panel';
import { ChartNoAxesCombined } from 'lucide-react';

export default function Page(){return <WalletRoot><Home/></WalletRoot>;}
function Home(){
 const {config,viewer,refresh,connect,disconnect,setNotice}=useWallet();
 const [selected,setSelected]=useState('olivia'),[character,setCharacter]=useState<Character|null>(null),[dialog,setDialog]=useState<'character'|'stage'|'wallet'|null>(null),[tab,setTab]=useState('all');
 const voting=useVoting();
 const modal=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const id=localStorage.getItem('her-character-preview');if(characters.some(c=>c.id===id))setSelected(id!);},[]);
 useEffect(()=>{if(dialog)modal.current?.showModal();else modal.current?.close();},[dialog]);
 function choose(c:Character){setSelected(c.id);localStorage.setItem('her-character-preview',c.id);setCharacter(c);setDialog('character');}
 useEffect(()=>{const doc=document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>void}};if(!doc.modelContext)return;const abort=new AbortController();doc.modelContext.registerTool({name:'her_preview_character',description:'Open HER character details. Does not spend tokens or change the live stream.',inputSchema:{type:'object',properties:{character:{type:'string',enum:characters.map(c=>c.id)}},required:['character'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{character:string})=>{const c=characters.find(c=>c.id===input.character);if(!c)throw new Error('Unknown character.');choose(c);return {character:c.id,preview:true};}},{signal:abort.signal});return()=>abort.abort();},[]);
 const walletClick=()=>viewer.wallet?setDialog('wallet'):connect();
 return <main>
 <div className="announcement">COLLECTION 001 IS HERE <span>Three characters. More on the way.</span><span className="launch-note">30-minute character rounds</span></div>
 <header><a className="wordmark" href="/" aria-label="HER home">her<span>↗</span></a><nav aria-label="Main navigation"><a href="#characters">Characters</a><a href="#trades">Trades</a><a href="#stage">The stage</a><a href="#burns">The burn</a></nav><a className="trades-mobile-link" href="#trades" aria-label="HER Trades" title="HER Trades"><ChartNoAxesCombined size={20}/></a><button className="button pink" onClick={walletClick}>{viewer.wallet?shortWallet(viewer.wallet):'Connect wallet'}</button></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow">MEET YOUR NEXT MAIN CHARACTER</div><h1>Human energy.<br/><em>Artificial</em> intelligence.</h1><p>A familiar face in unfamiliar territory.<br/>Welcome to HER. Welcome to the trenches.</p><a href="#characters" className="button light">Meet the characters</a></div><div className="hero-side"><span>H / 001</span><p>Present.<br/>Expressive.<br/>A little unpredictable.</p></div><div className="hero-foot"><span>AN AI CHARACTER COLLECTIVE</span><span>THREE FACES. ONE WORLD.</span></div></section>
 <VotingPanel voting={voting}/><TradesPanel/><section className="characters section" id="characters"><div className="section-title"><div><span className="eyebrow">THE FIRST COLLECTION / 01—03</span><h2>Find your<br/><em>kind of HER.</em></h2></div><div className="section-intro"><p>Olivia is where it starts. Maya and Ivy bring a different presence. Explore three system faces, with more joining over time.</p><div className="filters" aria-label="Character filters">{['all','original','pro'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='all'?'All characters':t==='original'?'Original':'Pro'}</button>)}</div></div></div>
 <div className="character-grid">{characters.filter(c=>tab==='all'||c.tier.toLowerCase()===tab).map(c=><article className={selected===c.id?'character selected':'character'} key={c.id}><button className="portrait" onClick={()=>choose(c)} aria-label={`View ${c.name} details`}><img src={c.image} alt={`${c.name}, HER AI system character`} loading="lazy"/><span className="index">0{characters.indexOf(c)+1}</span><span className="tier">{c.tier}</span><span className="portrait-action">View character <span aria-hidden="true">↗</span></span></button><div className="character-info"><div><h3>{c.name}</h3><p>{c.subtitle}</p></div><button className="select-button" onClick={()=>choose(c)} aria-label={`Explore ${c.name}`}>Explore</button></div><div className="character-meta"><span>AI SYSTEM FACE</span><span>{config.enabled?'10,000 HER MINIMUM':'VOTING OPENS SOON'}</span></div></article>)}</div>
 <div className="collection-note"><span>THIS IS ONLY THE BEGINNING.</span><p>Three faces today. The collection grows with HER.</p></div></section>
 <section className="stage section" id="stage"><div className="stage-copy"><span className="eyebrow">THE STAGE / PUMP.FUN</span><h2>From the chat.<br/><em>Into the conversation.</em></h2><p>One open seat beside HER. Burn tokens to request it, tell us what’s on your mind, and wait for the host to call you up.</p><button className="button pink" onClick={()=>setDialog('stage')}>{config.stageEnabled?'Request the stage':'Explore stage access'}</button><span className="under-button">Manual approval. One guest at a time.</span></div><div className="stage-pass"><div className="pass-head"><span>HER / GUEST PASS</span><span>001</span></div><div className="pass-seat"><span className="seat-mark" aria-hidden="true">+</span><h3>This could<br/>be your seat.</h3></div><div className="pass-status"><span>{config.stageEnabled?'REQUESTS OPEN':'OPENING AFTER LAUNCH'}</span><span>ONE AT A TIME</span></div><div className="pass-bottom"><div><span>ENTRY</span><strong>{config.stageAmount?`${config.stageAmount} ${config.symbol}`:'Burn amount TBA'}</strong></div><div><span>ADMISSION</span><strong>Host approval</strong></div></div></div></section>
 <section className="section burn" id="burns"><div className="section-title"><div><span className="eyebrow">LESS SUPPLY. MORE PARTICIPATION.</span><h2>Make it<br/><em>mean something.</em></h2></div><p>Burn at least 10,000 HER to vote for the next live character. Every verified vote has an on-chain receipt tied to your wallet. Stage access is separate.</p></div><div className="burn-rows"><div><span className="row-number">01</span><h3>Choose your character</h3><p>Choose Olivia, Maya, or Ivy. Enter any amount from 10,000 HER. Your full burn adds to your character’s total.</p><span>CHARACTER VOTE</span></div><div><span className="row-number">02</span><h3>Put your hand up</h3><p>Submit a stage request with your burn receipt. The host decides who joins next.</p><span>STAGE REQUEST</span></div><div><span className="row-number">03</span><h3>Keep the receipt</h3><p>See the amount, wallet, and transaction. A confirmed burn can only be used once.</p><span>VERIFIED ON-CHAIN</span></div></div><div className="burn-note"><span>BEFORE YOU BURN</span><p>Burns permanently destroy tokens and cannot be refunded. A stage request does not guarantee admission. Character burns have a 10,000 HER minimum. The largest verified total wins each 30-minute round.</p></div></section>
 <footer><a className="wordmark" href="/">her<span>↗</span></a><p>AI characters. Real conversations.</p><a href="/host">Host controls</a><span>HER / 2026</span></footer>
 <dialog aria-label={dialog==='character'?'Character details':dialog==='stage'?'Stage request':'Wallet activity'} ref={modal} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===modal.current)setDialog(null);}}><button className="close" aria-label="Close dialog" onClick={()=>setDialog(null)}>×</button>{dialog==='character'&&character&&<div className="character-dialog"><div className="character-portrait"><img src={character.image} alt={`${character.name}, HER AI system character`}/></div><div className="dialog-copy"><span className="eyebrow">{character.tier} / AI SYSTEM FACE</span><h2>{character.name}</h2><p>{character.description}</p><BurnFlow key={character.id} kind="character" character={character.id} voting={voting}/></div></div>}{dialog==='stage'&&<div className="dialog-copy stage-dialog"><span className="eyebrow">YOUR MOMENT WITH HER</span><h2>Request the stage.</h2><p>The host reviews every request. If accepted, your private guest-room invitation appears in your wallet activity. Only one guest is admitted at a time.</p><BurnFlow kind="stage"/></div>}{dialog==='wallet'&&<div className="dialog-copy"><span className="eyebrow">YOUR WALLET</span><h2>Your place in HER.</h2><p className="wallet-address">{viewer.wallet}</p><div className="wallet-actions"><button className="select-button" onClick={()=>void refresh().catch(e=>setNotice(e.message))}>Refresh activity</button><button className="select-button" onClick={()=>{setDialog(null);connect();}}>Reconnect wallet</button><button className="select-button" onClick={()=>void disconnect().then(()=>setDialog(null))}>Disconnect</button></div><h3 className="small-heading">Stage requests</h3>{viewer.requests.length?viewer.requests.map(r=><div className="activity" key={r.id}><strong>{r.name}</strong><span>{r.status.replace('_',' ')}</span><p>{r.topic}</p>{r.invite_url&&['accepted','on_stage'].includes(r.status)&&<a className="button light" href={r.invite_url} target="_blank" rel="noreferrer">Open guest room</a>}</div>):<p className="empty-copy">No stage requests yet.</p>}<h3 className="small-heading">Burn receipts</h3>{viewer.receipts.length?viewer.receipts.map(r=><div className="activity" key={r.id}><strong>{r.amount} {config.symbol}</strong><span>{r.kind==='stage'?'Stage request':r.character}</span><a href={`https://solscan.io/tx/${r.signature}`} target="_blank" rel="noreferrer">View verified transaction</a></div>):<p className="empty-copy">No burns recorded. Nothing has been spent.</p>}</div>}</dialog>
 </main>;
}

function BurnFlow({kind,character,voting}:{kind:'stage'|'character';character?:string;voting?:Voting|null}){
 const {config,viewer,connect,signTransaction,refresh}=useWallet();const [name,setName]=useState(''),[topic,setTopic]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[counted,setCounted]=useState(false),[receipt,setReceipt]=useState<{id:string;signature:string}|null>(null);
 const [customAmount,setCustomAmount]=useState('10000');
 let amountError='';try{if(kind==='character')voteAmount(customAmount);}catch(e){amountError=e instanceof Error?e.message:'Invalid amount';}
 const enabled=config.enabled&&(kind==='stage'?config.stageEnabled:!!voting?.accepting),amount=kind==='stage'?config.stageAmount:customAmount;
 const receiptKey=`her-pending-burn:${viewer.wallet}:${kind}:${character||''}`;
 useEffect(()=>{try{const r=JSON.parse(localStorage.getItem(receiptKey)||'null');if(r?.id&&r?.signature)setReceipt(r);}catch{}},[receiptKey]);
 async function verify(r:{id:string;signature:string}){let last:unknown;for(let attempt=0;attempt<12;attempt++){try{const result=await api<{counted:boolean}>('verify',r);setCounted(result.counted);await refresh();setSuccess(true);localStorage.removeItem(receiptKey);return;}catch(e){last=e;await new Promise(resolve=>setTimeout(resolve,2500));}}throw last;}
 async function burn(){setBusy(true);setError('');try{if(receipt){await verify(receipt);return;}const p=await api<{id:string;unsignedTransaction:string}>('prepare',{kind,character,name,topic,amount:kind==='character'?voteAmount(customAmount):amount});const signedTransaction=await signTransaction(p.unsignedTransaction);const sent=await api<{signature:string}>('broadcast',{id:p.id,signedTransaction});const r={id:p.id,signature:sent.signature};setReceipt(r);localStorage.setItem(receiptKey,JSON.stringify(r));await verify(r);}catch(e){setError(e instanceof Error?e.message:'The request could not be completed.');}finally{setBusy(false);}}
 if(success)return <div className="success-state"><span className="eyebrow">BURN VERIFIED</span><h3>{kind==='stage'?'You’re in the queue.':counted?'Your vote is counted.':'Burn receipt saved.'}</h3><p>{kind==='stage'?'Your request is waiting for the host. Check your wallet activity for updates.':counted?'Your burn is included in this round. The highest total chooses the next live character.':'This burn was verified after the round closed and could not count. Your receipt is saved.'}</p>{kind==='character'&&<button className="select-button" onClick={()=>{setSuccess(false);setReceipt(null);setAck(false);}}>Vote again</button>}</div>;
 return <div className="burn-form">{kind==='stage'&&<><label htmlFor="guest-name">Name on stage</label><input id="guest-name" value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="What should HER call you?"/><label htmlFor="guest-topic">What’s on your mind?</label><textarea id="guest-topic" value={topic} onChange={e=>setTopic(e.target.value)} maxLength={280} placeholder="AGI, life in the trenches, or a question for HER…" rows={3}/></>}{kind==='character'&&<><label htmlFor="burn-amount">Amount of HER to burn</label><input id="burn-amount" inputMode="decimal" value={customAmount} disabled={busy||!!receipt} onChange={e=>{setCustomAmount(e.target.value);setAck(false);}} maxLength={40}/><p className="empty-copy">Minimum 10,000 HER. Any larger amount counts in full toward this character’s total.</p>{amountError&&<p className="form-error">{amountError}</p>}</>}<div className="burn-price"><span>{kind==='stage'?'STAGE REQUEST':'CHARACTER VOTE / THIS ROUND'}</span><strong>{amount?`${amount} ${config.symbol}`:'Burn amount TBA'}</strong></div>{enabled||receipt?<><label className="checkbox-label"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>I understand that burning permanently destroys my tokens.{kind==='stage'?' Admission is manual and not guaranteed.':' This is a vote, not a guaranteed character change.'}</span></label>{!viewer.wallet?<button className="button pink" onClick={connect}>Connect wallet to continue</button>:<button className="button pink" disabled={busy||(!receipt&&(!ack||!!amountError||(kind==='stage'&&(!name.trim()||!topic.trim()))))} onClick={()=>void burn()}>{busy?'Waiting for confirmation…':receipt?'Verify submitted burn':`Burn ${amount} ${config.symbol}`}</button>}</>:<div className="inline-note"><strong>{kind==='stage'?'Stage requests are closed':'Voting is paused'}</strong><p>{kind==='stage'?'No tokens will be spent.':'Wait for an open round and an online camera controller before burning.'}</p></div>}{receipt&&!success&&<p className="inline-note">Your transaction was submitted. Retry verification; do not burn again. <a href={`https://solscan.io/tx/${receipt.signature}`} target="_blank" rel="noreferrer">View transaction</a></p>}{error&&<p className="form-error" role="alert">{error}</p>}</div>;
}
