"use client";
import { useEffect,useState } from 'react';
import { useWallet,api,WalletRoot } from '@/components/wallet';
import { shortWallet,type StageRequest,type Receipt } from '@/lib/catalog';
const sample=()=>[{id:'sample-1',wallet:'Demo wallet A',name:'Guest 01',topic:'Can AGI keep up with the trenches?',status:'pending',created_at:0,signature:'DEMO RECEIPT — NO TOKENS BURNED',amount:'Demo'},{id:'sample-2',wallet:'Demo wallet B',name:'Guest 02',topic:'A question about being human.',status:'pending',created_at:0,signature:'DEMO RECEIPT — NO TOKENS BURNED',amount:'Demo'}] as StageRequest[];
export default function Page(){return <WalletRoot><Host/></WalletRoot>;}
function Host(){const {viewer,config,connect}=useWallet();const [demo,setDemo]=useState(false),[samples,setSamples]=useState(sample),[requests,setRequests]=useState<StageRequest[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[notice,setNotice]=useState(''),[invite,setInvite]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('queue');
 async function load(){setBusy(true);try{const data=await api<{requests:StageRequest[];receipts:Receipt[]}>('admin');setRequests(data.requests);setReceipts(data.receipts);}catch(e){setNotice(e instanceof Error?e.message:'Could not load the queue.');}finally{setBusy(false);}}
 useEffect(()=>{if(viewer.isHost)void load();},[viewer.isHost]);
 const rows=demo?samples:requests,active=rows.find(r=>r.status==='on_stage');
 async function moderate(id:string,status:string){setNotice('');if(demo){if(status==='on_stage'&&active){setNotice('End the current guest’s turn before admitting another.');return;}setSamples(old=>old.map(r=>r.id===id?{...r,status}:r));return;}setBusy(true);try{await api('moderate',{id,status,inviteUrl:invite});await load();}catch(e){setNotice(e instanceof Error?e.message:'Could not update this request.');}finally{setBusy(false);}}
 return <main className="host-page"><div className="host-nav"><a className="wordmark" href="/">ACP<span>↗</span></a><a href="/">Back to characters</a><button className="button light" onClick={connect}>{viewer.wallet?shortWallet(viewer.wallet):'Connect host wallet'}</button></div><div className="host-heading"><div><span className="eyebrow">BACKSTAGE / HOST CONTROLS</span><h1>You run the room.</h1></div><button className="select-button" onClick={()=>{setDemo(!demo);setNotice('');}}>{demo?'Leave demo':'Preview the controls'}</button></div>
 {demo?<div className="demo-banner"><strong>Interactive demo</strong><span>Sample guests only. No burns, invitations, or live-stage changes are made.</span><button onClick={()=>{setSamples(sample());setNotice('');}}>Reset demo</button></div>:!viewer.isHost?<div className="host-lock"><h2>Reserved for the host.</h2><p>Only the designated host wallet can view real burn receipts, approve guests, or manage the stage. No email signup is required.</p><button className="button pink" onClick={connect}>Connect host wallet</button>{!config.hostConfigured&&<p className="setup-state">Host access opens when the host wallet is configured.</p>}</div>:null}
 {(demo||viewer.isHost)&&<><div className="host-overview"><div className="stage-monitor"><span className="eyebrow">{demo?'DEMO STAGE':'STAGE QUEUE CONTROL'}</span><h2>{active?active.name:'The seat is open.'}</h2><p>{active?active.topic:'Accept a request, then bring that guest on stage.'}</p>{active&&<button className="button light" disabled={busy} onClick={()=>void moderate(active.id,'ended')}>End guest’s turn</button>}<small>Admission is tracked here. Connect the accepted guest’s room to your broadcast manually.</small></div><div className="queue-count"><span>{rows.filter(r=>r.status==='pending').length.toString().padStart(2,'0')}</span><p>Awaiting your review</p><strong>1 guest maximum on stage</strong></div></div><div className="host-tabs"><button onClick={()=>setTab('queue')} aria-pressed={tab==='queue'}>Stage requests</button><button onClick={()=>setTab('burns')} aria-pressed={tab==='burns'}>Burn receipts</button>{!demo&&<button disabled={busy} onClick={()=>void load()}>Refresh</button>}</div>{notice&&<p role="alert" className="form-error host-error">{notice}</p>}{!demo&&tab==='queue'&&<div className="invite-field"><label htmlFor="guest-invite">Private guest room invitation</label><input id="guest-invite" className="invite-input" value={invite} onChange={e=>setInvite(e.target.value)} placeholder="https://…"/><p>Paste the guest’s room link before accepting. It is shown only to that wallet and the host.</p></div>}
 {tab==='queue'?<div className="queue-list">{rows.length?rows.map(r=><article className="queue-row" key={r.id}><div className="queue-person"><span>{r.status.replace('_',' ')}</span><h3>{r.name}</h3><p>{r.topic}</p><code>{shortWallet(r.wallet)}</code></div><div className="queue-receipt"><span>{demo?'SAMPLE RECEIPT':'VERIFIED BURN'}</span><strong>{demo?'No tokens spent':`${r.amount} ${config.symbol}`}</strong>{!demo&&<a href={`https://solscan.io/tx/${r.signature}`} target="_blank" rel="noreferrer">View transaction</a>}</div><div className="queue-actions">{r.status==='pending'&&<><button className="button pink" disabled={busy} onClick={()=>void moderate(r.id,'accepted')}>Accept guest</button><button className="select-button" disabled={busy} onClick={()=>void moderate(r.id,'rejected')}>Decline</button></>}{r.status==='accepted'&&<><button className="button pink" disabled={busy} onClick={()=>void moderate(r.id,'on_stage')}>Bring on stage</button><button className="select-button" disabled={busy} onClick={()=>void moderate(r.id,'rejected')}>Remove</button></>}{r.status==='on_stage'&&<button className="button light" disabled={busy} onClick={()=>void moderate(r.id,'ended')}>End turn</button>}{['rejected','ended'].includes(r.status)&&<span>{r.status==='ended'?'Turn complete':'Request declined'}</span>}</div></article>):<div className="empty-state"><h3>No requests yet.</h3><p>Verified stage burns appear here when requests open.</p></div>}</div>:<div className="ledger"><div className="ledger-head"><span>Wallet</span><span>Purpose</span><span>Burned</span><span>Receipt</span></div>{demo?samples.map(r=><div className="ledger-row" key={r.id}><span>{r.wallet}</span><span>Stage request</span><span>Demo only</span><span>No transaction</span></div>):receipts.length?receipts.map(r=><div className="ledger-row" key={r.id}><span title={r.wallet}>{shortWallet(r.wallet)}</span><span>{r.kind==='stage'?'Stage request':r.character}</span><span>{r.amount} {config.symbol}</span><a href={`https://solscan.io/tx/${r.signature}`} target="_blank" rel="noreferrer">View on-chain</a></div>):<div className="empty-state"><h3>No burns recorded.</h3><p>Wallet, amount, purpose, and transaction will appear after verification.</p></div>}</div>}</>}
 <div className="host-foot">Every guest is a manual decision. A token burn never bypasses your approval.</div></main>;
}
